# Body text of the review. Markers:
#   [[c:key1,key2]]  citation   [[fig:name]] place figure   [[figref:name]] "Fig. N"
#   [[tab:name]] place table     [[tabref:name]] "Table N"

TITLE = 'Hyperlexia in Children and Adolescents: A Comprehensive Narrative Review of Definitions, Prevalence, Mechanisms, Comprehension, Allied Strengths, and Strength-Based Intervention'
SUBTITLE = 'With design implications for a bilingual (English / Québec French), music-integrated game suite for an adolescent reader'

ABSTRACT = [
    ('Background', 'Hyperlexia — precocious, largely self-taught word reading that outstrips comprehension, together with an intense orientation toward written material — was first described in 1967 and is still debated as a disability, a "superability", or a learning style. This review compiles every unique finding available across the indexed literature into a single reference.'),
    ('Methods', 'Narrative synthesis of all Europe PMC records mentioning <i>hyperlexia</i> in their title or abstract (86 unique records, 1967–2025, drawn from 236 full-text hits), supplemented by 24 targeted studies on reading comprehension in autism, figurative language, bilingualism, music, and twice-exceptional adolescents, 2 foundational framework papers, and 8 clinical/educational sources (120 sources in total). Quantitative results were extracted verbatim from the primary reports and re-plotted; no new data were collected and no pooling was attempted.'),
    ('Results', 'Hyperlexia is reported in about 6–21% of autistic children, and 84% of published hyperlexic case reports involve autism, yet it also appears in typical development, ADHD, Turner and 22q11.2 deletion syndromes, Prader-Willi, West syndrome, tuberous sclerosis, and — as a distinct acquired sign — after frontal lesions in adults. In a Montréal clinic cohort, interest in letters emerged at a median of 30 months in autistic children (the same age as in typical development) even though 76% were minimally verbal; the odds of stronger interest were 2.78× for letters and 3.49× for numbers relative to non-autistic clinical peers. Mechanistic work converges on an orthographic, perception-first route to word recognition that can function without semantic access, with fMRI showing hyperactivation of left superior temporal cortex. Comprehension difficulty tracks semantic/oral-language knowledge (57% of variance) and is greatest for socially loaded, inferential and figurative text. Interventions that lead with print — written prompts, word–picture matching, question scaffolding, graphic representations (Tau-U = 0.85) — show consistent gains. Numbers (hypercalculia profile in 20% of one national sample), music (absolute pitch in 5–11% of autistic people; music-therapy global improvement RR = 1.22) and additional languages are allied strengths.'),
    ('Conclusions', 'Hyperlexia is best treated as a heterogeneous, strength-anchored reading profile. Effective support "writes it out", teaches meaning, inference and pragmatics explicitly, and harnesses allied systemising interests. We translate these findings into nine design principles and a 25-game bilingual suite built for a 15-year-old hyperlexic, hypernumerate pianist.'),
]
KEYWORDS = 'hyperlexia; autism; reading comprehension; simple view of reading; orthographic processing; hypernumeracy; music; absolute pitch; bilingualism; Québec French; strength-based intervention; serious games'

BODY = r'''
<h2><span class="sn">1</span>Introduction</h2>
<h3>1.1 A short history</h3>
<p>In 1967 Norman and Margaret Silberberg described young children whose word-recognition skill was far ahead of every other ability and named the phenomenon <i>hyperlexia</i> [[c:silberberg1967]]. Within a year the field was already arguing about its meaning — Niensted asked whether it was "an educational disease" [[c:niensted1968]] — and early neurological series framed it as exceptional reading in children with brain damage or developmental delay [[c:mehegan1972,huttenlocher1973]]. Elliott and Needleman proposed a discrete "syndrome of hyperlexia" in 1976 [[c:elliott1976]].</p>
<p>The 1980s were the most productive decade ([[figref:decades]]). Researchers reframed hyperlexia as a variant of developmental language disorder [[c:richman1981,cohen1987,siegel1984]], dissected its reading routes [[c:goldberg1984,welsh1987,cobrinik1982]], tested whether comprehension was really impaired [[c:snowling1986]], and ran the first population work in North Dakota [[c:burd1985b,fisher1988]]. From 1999 onward, cognitive models [[c:nation1999,grigorenko2003]], neuroimaging [[c:turkeltaub2004]] and systematic reviews [[c:ostrolenk2017,zhang2019]] followed. Much of the current evidence comes from two Montréal groups — Mottron, Ostrolenk and colleagues [[c:ostrolenk2017,ostrolenk2023,ostrolenk2024,mottron2013]] and Macdonald, Luk and Quintin at McGill [[c:macdonald2021,macdonald2022]] — which makes the literature unusually relevant to a French-speaking Québec family.</p>
[[fig:decades]]
<h3>1.2 Why a single "mega" review</h3>
<p>Findings about hyperlexia are scattered across neurology, psychiatry, linguistics, education and music cognition, and many papers are small case studies with one unique observation each. This review gathers every such observation in one place, re-plots the published numbers, and closes by translating the evidence into concrete design principles for a game suite commissioned for one reader: a 15-year-old hyperlexic adolescent who is bilingual in English and Québec French, reasons at roughly a 17-year-old level, counts into the nonillions, and plays the piano.</p>

<h2><span class="sn">2</span>Methods</h2>
<h3>2.1 Search strategy</h3>
<p>The Europe PMC REST API was queried on 27 September 2026 for <i>hyperlexia OR hyperlexic</i> across all fields, returning 236 records. Records in which the term appeared only in full text (typically a passing mention) were set aside; the 87 records that used it in the title or abstract were retained, and one publisher correction was removed, leaving 86 unique hyperlexia records (60 with the term in the title). Targeted searches added the adjacent literatures that the hyperlexia papers themselves point to: reading comprehension in autism, inferencing and figurative language, bilingual language development, music perception and therapy, and twice-exceptional (2e) adolescents (24 records), plus two framework papers [[c:gough1986,mottron2006]]. Web searches identified eight clinical and educational sources that summarise current practice ([[figref:flow]]).</p>
<h3>2.2 Extraction and synthesis</h3>
<p>For every record the design, sample, main quantitative results and — the focus of this review — its <i>unique</i> contribution were extracted (Appendix A). Sixteen older or non-English records had no indexed abstract; they are listed from their bibliographic data and flagged. Because definitions, measures and populations differ widely [[c:zhang2019]], results were synthesised narratively and numbers are re-plotted exactly as published, never pooled.</p>
[[fig:flow]]

<h2><span class="sn">3</span>Definitions and conceptual frameworks</h2>
<h3>3.1 What counts as hyperlexia?</h3>
<p>Definitions have drifted along three axes: <i>what</i> is advanced (single-word reading), <i>relative to what</i> (comprehension, vocabulary, or IQ), and <i>in whom</i> (any child, or only children with developmental conditions) [[c:grigorenko2003]] ([[tabref:defs]]). The most cited modern definition requires the co-occurrence of (1) reading skill advanced relative to comprehension or general intelligence, (2) early acquisition without explicit teaching, and (3) a strong orientation toward written material, generally in the context of a neurodevelopmental condition [[c:ostrolenk2017]]. Clinical descriptions add typical signs: preference for books and letters over toys, spelling words aloud or tracing them in the air, teaching oneself to read, and difficulty answering <i>who / what / where / why / how</i> questions [[c:cleveland,treffertcenter]].</p>
[[tab:defs]]
<h3>3.2 The Simple View of Reading</h3>
<p>The Simple View holds that reading comprehension is the <i>product</i> of decoding and language comprehension [[c:gough1986]]. It yields good readers and three kinds of poor readers — dyslexic (weak decoding, intact language), hyperlexic (strong decoding, weak language comprehension) and "garden-variety" (both weak) ([[figref:svr]]) [[c:sparks2018]]. Because the terms multiply, even perfect decoding cannot compensate for weak language comprehension; hence the argument that hyperlexia is a genuine reading disorder requiring language support [[c:whiteside2023]]. The meta-analysis by Zhang and Joshi supports the good-decoding / poor-listening-and-reading-comprehension profile, but found that only 66.22% of identified hyperlexics actually showed <i>precocious</i> decoding and that about 96% of studies sampled atypical populations, so definitions strongly shape results [[c:zhang2019]].</p>
[[fig:svr]]
<h3>3.3 Disability, superability, or learning style?</h3>
<p>Grigorenko, Klin and Volkmar concluded that hyperlexia is best seen as a <i>superability</i> of a specific group of children with developmental disorders [[c:grigorenko2003]]. Nation argued that it sits at the tail of normal variation in phonological, orthographic and semantic processing, amplified by compulsive print exposure [[c:nation1999]]. Kennedy's two cases supported an "asset rather than deficit" reading [[c:kennedy2003]], whereas neuropsychological comparisons placed its essential feature in language impairment rather than dyslexia [[c:cohen1997,cohen1987]]. Clinicians working with gestalt language processors describe it as a learning <i>style</i>: many hyperlexic children acquire language in chunks and learn best when language is modelled in writing [[c:meaningfulspeech]]. These views are compatible: the reading engine is a strength; the language-to-meaning link is the target.</p>

<h2><span class="sn">4</span>Subtypes and differential diagnosis</h2>
<p>Treffert distinguished three types ([[tabref:types]]) [[c:treffert2011,treffertcenter]]. Type 1 describes typically developing precocious readers, exemplified by a preschooler with a reading age of 11.2 years at 4;2 and comprehension well above age level [[c:pennington1987]]. Type 2 is hyperlexia as a splinter skill within autism, often with prodigious memory for dates, plates or trivia. Type 3 describes early readers with "autistic-like" traits that fade; misreading them as autistic can lead to inappropriate placement [[c:treffert2011,treffert2014,transmitter]]. Treffert's broader work on savant syndrome estimates that up to one in ten autistic people have savant abilities, that about half of savants are autistic, that IQ can be superior, and that savant skills tend to grow from duplication through improvisation to creation [[c:treffert2014]].</p>
[[tab:types]]
<p>Within high-functioning hyperlexia, Richman and Wood identified two subtypes among 30 children: a language-learning-disorder pattern with good visual memory and phonetic errors, and a nonverbal-learning-disorder pattern with visuospatial weakness and sight-word errors [[c:richman2002]]. Turner syndrome shows yet another form — broad "hyperdevelopment" of reading with <i>good</i> comprehension [[c:temple1996,temple2006]]. Snowling and Frith found that more verbally able advanced decoders comprehended normally and proposed that "true" hyperlexia is marked by failure to build large units of meaning; they found no autistic/non-autistic differences [[c:snowling1986]]. Other cases show comprehension that is not unexpectedly deficient [[c:welsh1987]] or above average [[c:mammarella2022]].</p>
<div class="box"><b>Box 1 · Acquired hyperlexia in adults.</b> Neurologists also use "hyperlexia" for a different phenomenon: adults who, after lesions of the left medial frontal lobe, anterior cingulate or corpus callosum, compulsively read aloud irrelevant environmental text — trash bags, signs, newspapers — often with echolalia [[c:suzuki2000,suzuki2009,vuilleumier1997,diaz2006]]. It is interpreted as bottom-up stimulus processing escaping top-down inhibition [[c:yamadori2000,bindschaedler1992]]. It shares a name, not a developmental course, with childhood hyperlexia.</div>

<h2><span class="sn">5</span>Prevalence and clinical associations</h2>
<h3>5.1 In autism</h3>
<p>Estimates depend on criteria ([[figref:prev]]). The systematic review of 82 cases and 912 group-study participants (315 hyperlexic) reported hyperlexia in 6–21% of autistic children, and 84% of published hyperlexic cases were autistic [[c:ostrolenk2017]]. Using a 90th-percentile criterion for early letter/number naming, 9% of 155 autistic preschoolers showed early hyperlexic traits [[c:solazzo2021]]. A nationally representative US sample of autistic 6–9-year-olds contained a hyperlexia achievement profile in 9% [[c:wei2015]], and a Swedish population cohort found 10 of 53 autistic 8-year-olds (19%) with a "hyperlexic/poor comprehender" profile [[c:asberg2019b]]. Broader <i>interest</i> in letters is much commoner (20–37%; §6). Hyperlexia is significantly more frequent in pervasive developmental disorders than in other developmental diagnoses, with no sex difference [[c:grigorenko2002]]. Nation and colleagues' sample of 41 autistic children ranged from floor to ceiling on every reading measure, underlining heterogeneity [[c:nation2006]].</p>
[[fig:prev]]
<h3>5.2 Beyond autism</h3>
<p>A hyperlexic-like style was found in 10 of 36 girls with ADHD, who also had more autistic social-communication features [[c:asberg2019a]]. More than two-thirds of young people with 22q11.2 deletion syndrome read above IQ expectations [[c:tobia2018]]. Case reports extend the list to Prader-Willi syndrome [[c:burd1989]], West syndrome with reading of Japanese and Chinese characters at age three [[c:ichiba1990]], tuberous sclerosis with hypermnesia and hypercalculia in a non-speaking girl [[c:pacheva2014]], specific language impairment [[c:cohen1997]], semantic-pragmatic disorder [[c:shields1991]], and a gifted boy after early institutionalisation [[c:stein2015]] ([[tabref:conds]]). Even typical high-school students fit a hyperlexic profile when reading a newly learned foreign language — "reading without meaning" is a normal early stage of L2 literacy [[c:sparks2018]].</p>
[[tab:conds]]
<h3>5.3 Families, twins and genes</h3>
<p>Family histories of 12 hyperlexic children revealed language, reading, writing and spelling disorders in male relatives and unusually high non-left-handedness [[c:healy1986]]. Five North Dakotans had PDD, Tourette disorder and hyperlexia together; the authors computed the chance probability of this triple co-occurrence as 3.39 × 10<sup>−12</sup> (about 1 in 295 billion) and inferred genetic linkage [[c:burd1988]]. Identical twins concordant for autism and hyperlexia have been described twice [[c:smith1988,ostrolenk2023]]. In 129 autistic children, hyperlexia clustered with a family history of affective disorder and of unusual intellectual achievement, suggesting a distinct subgroup [[c:delong2002]]. Hyperlexic autistic children in one small comparison showed more persistent echolalia, better visual-motor skills and, in two cases, macrocephaly [[c:tirosh1993]]. At the animal level, mice lacking the autism-risk gene SHANK3 show enhanced pitch discrimination, a reminder that heightened low-level perception may be heritable [[c:rendall2019]].</p>

<h2><span class="sn">6</span>Early development: interest in letters and numbers</h2>
<p>The largest study of early print interest reviewed all 701 children under 7 referred to a Montréal autism clinic over four years (391 autistic, 310 non-autistic) and interviewed caregivers of 313 children [[c:ostrolenk2024]]. Clinician reports described an intense or exclusive interest in letters in 20% of autistic children versus 3% of clinical peers, and in numbers in 17% versus 2% ([[figref:interest]]). Adjusted odds of a greater interest were 2.78 for letters and 3.49 for numbers ([[figref:or]]). When caregivers were asked directly, the proportion with intense letter interest rose to 37%.</p>
<p>Timing is the striking result: the median age of emergence was 30 months for autistic children, 28.5 months for typically developing children and 36 months for the non-autistic clinical group, and it did not depend on the child's level of oral language ([[figref:age]]). That interest arose while 24% of autistic children had no oral language and a further 37% used isolated words only ([[figref:lang]]). Of 33 fully non-verbal autistic children, 8 could sing the alphabet song, 9 named letters, 9 counted, 3 pretend-read, 2 read some words and 1 spelled some words. Twenty-five percent of typically developing children also had an intense interest in letters, but theirs usually appeared after speech and centred on shared books, whereas autistic children engaged alone and often refused adult intervention — a pattern that may lead parents to underestimate their competence [[c:ostrolenk2024]]. A separate study reported that 29.7% of autistic 9-year-olds had a special interest in reading, suggesting persistence into childhood (cited in [[c:ostrolenk2024]]).</p>
[[fig:interest]]
[[fig:or]]
[[fig:age]]
[[fig:lang]]
<p>Early letter/number skill is not a bad sign. In 155 preschoolers it was associated with more repetitive behaviours but also with more social-oriented behaviour and better expressive and written communication one year later [[c:solazzo2021]]. Six Brazilian boys whose hyperlexia was noticed before 36 months all recognised letters and numbers, though most did not understand what they read [[c:lamonica2013]]. The Montréal twins' language consisted only of letters and numbers until their fourth year, after which vocabulary broadened to full sentences and their perceptual interests "merged to serve the development of other skills" [[c:ostrolenk2023]]. The authors frame hyperlexia as potentially the first step of a <i>non-social</i> pathway into language [[c:ostrolenk2023,ostrolenk2024]].</p>

<h2><span class="sn">7</span>Cognitive and neural mechanisms</h2>
<h3>7.1 Routes from print to sound</h3>
<p>Almost every mechanism study agrees that hyperlexic readers can reach pronunciation without meaning. Two cases read irregular words they could not define as accurately as words they could, evidence of a direct lexical route from orthography to phonology [[c:castles2010]]; whole-word orthographic and phonological representations were acquired despite severe semantic impairment [[c:glosser1997]]; and girls with severe intellectual disability read words, non-words and texts accurately [[c:cossu1986]], as did a girl with an IQ of 58 [[c:siegel1984]]. Beyond that consensus, routes differ by child. Eight children in one study reached the lexicon by both visual-orthographic (preferred) and phonological routes and understood single words and sentences but not paragraphs; only three showed metalinguistic awareness [[c:goldberg1984]]. Five others preferred the phonological route, resembling surface dyslexia [[c:welsh1987]]. Hyperlexic children retain sound–symbol pairings unusually well [[c:kistner1988]] and are faster and finer-grained at reading degraded "incomplete words" [[c:cobrinik1982]]. Preschoolers with autism and hyperlexia had advanced word reading and letter naming without matching phonological awareness or letter–sound knowledge — a non-phonological path [[c:macdonald2021]] — and Chinese hyperlexic reading appears to map whole characters directly to sound [[c:luo2023]]. In adolescents, outstanding readers had stronger lexical orthographic and phonological representations but no advantage in sublexical processing, rapid naming or memory [[c:saldana2009]]. The general architecture of single-word reading is nevertheless the same as in typical readers [[c:newman2007]].</p>
<h3>7.2 Perception first: EPF and veridical mapping</h3>
<p>The Enhanced Perceptual Functioning model holds that perception has a larger, more autonomous role in autistic cognition [[c:mottron2006]]. A meta-analysis of imaging studies found more temporal, occipital and parietal and less frontal activity in autism across faces, objects and words [[c:samson2012]]. <i>Veridical mapping</i> proposes that perceptual systems detect isomorphisms between structures — letters and sounds, pitches and note names, numbers and colours — explaining why hyperlexia, absolute pitch and synaesthesia co-occur and develop alike [[c:mottron2013,bouvet2014]]. Autistic children therefore follow a "chronologically inverted" path, mastering the code before the meaning, and make extended use of the visual word-form system [[c:ostrolenk2017]]. Goldberg's older savant account emphasised intact declarative but impaired procedural memory [[c:goldberg1987]]; clinical reviews stress visual memory, visual discrimination and motivation toward visual material [[c:martos2003,whitehouse1984]]. A minimally verbal trilingual hyperlexic child processed recursive visual patterns like typical peers despite no recursion in speech [[c:rossello2025]].</p>
[[fig:model]]
<h3>7.3 Neuroimaging</h3>
<p>The only fMRI study of developmental hyperlexia examined a 9-year-old reading six years ahead of his age. During covert reading he over-activated left inferior frontal and superior temporal cortex (vs both age- and reading-age-matched controls) and right inferior temporal sulcus (vs reading-age controls). Hyperlexic reading thus draws simultaneously on left-hemisphere phonological and right-hemisphere visual systems — the mirror image of dyslexic hypoactivation of left superior temporal cortex [[c:turkeltaub2004]]. Orthographic-route accounts from Spanish-speaking cases converge on the same idea [[c:talero2006]].</p>
<h3>7.4 Memory and profiles</h3>
<p>Hyperlexic autistic boys followed for 7–17 years had unusually good visual and auditory memory and a large stored written vocabulary despite limited speech [[c:whitehouse1984]]. SLI + hyperlexia was distinguished by stronger visual/spatial memory, while verbal memory fell as semantic load rose [[c:cohen1997]]. Children with West syndrome showed the opposite, excellent auditory memory with weak visual retention [[c:ichiba1990]]. Hypergraphia may accompany hyperlexia [[c:burd1985a]], and IQ varies enormously — from severe disability to very superior — with prognostic implications [[c:graziani1983,whitehouse1984,grigorenko2002]].</p>

<h2><span class="sn">8</span>Reading comprehension</h2>
<h3>8.1 What predicts understanding</h3>
<p>Across 36 studies, autistic readers scored 0.7 SD below controls in comprehension; semantic knowledge explained 57% and decoding 55% of the variance, and highly social texts were harder than non-social ones — having autism alone did not predict difficulty [[c:brown2013]] ([[figref:brown]]). A later meta-analysis of 26 studies (ages 6–18) found similar mean correlations of comprehension with word reading (r = .65) and with oral language (r = .61) [[c:sorenson2021]]. In poor comprehenders generally, a subset with lower general ability shows a hyperlexic profile in which accuracy, not comprehension, is the surprise [[c:nation2002]].</p>
[[fig:brown]]
<p>Development matters. In the nationally representative Wei et al. sample, every achievement profile lost ground in passage comprehension over time and the hyperlexia group improved most slowly in conversation ([[figref:wei]]) [[c:wei2015]]. In the Swedish cohort, oral-language weaknesses already visible at age 3 predicted who became "hyperlexic/poor comprehenders" at 8 ([[figref:asberg]]) [[c:asberg2019b]]. Early assessment can be done online: a six-subtest multimedia tool (decoding, homographs, auditory/visual vocabulary and sentence comprehension) separated autistic from typical children with up to 92% accuracy [[c:lin2013]].</p>
[[fig:wei]]
[[fig:asberg]]
<h3>8.2 From words to paragraphs</h3>
<p>Comprehension breaks down as units grow. Children who understood single words and sentences failed with paragraphs [[c:goldberg1984]]. Low-verbal fluent readers read word-by-word, failed to use sentence context to pronounce homographs and did not draw on general knowledge to answer questions about stories [[c:snowling1986]]. The core difficulty, in Shields' words, is integrating semantic information with knowledge of the world [[c:shields1991]].</p>
<h3>8.3 Inference, figurative language and social text</h3>
<p>Autistic children struggle most with inferences that require context, especially when mind-reading is involved, and with explaining how they used context [[c:loukusa2018]]. Idioms are often read literally; comprehension depends on inferencing and is helped by transparency, familiarity and context [[c:martelle2022]]. An ALE meta-analysis of six fMRI studies (95 autistic, 98 non-autistic participants) found a shared figurative-language network but consistent hypoactivation of left superior and middle temporal gyri in autism [[c:cheng2026]]. In 81 autistic 8–16-year-olds followed over three waves, growth in narrative retelling and inference related to reading-comprehension outcomes [[c:mcintyre2020]].</p>
<h3>8.4 Adolescence</h3>
<p>Adolescent evidence is thin but consistent. In 45 autistic adolescents (mean 14.9 years), task-switching predicted comprehension indirectly through decoding [[c:ober2021]]; middle-school students improved with vocabulary and main-idea instruction and valued choosing their own texts [[c:solis2021]]; and a hyperlexic student followed into high-school Spanish was strongest on pronunciation, word recognition and spelling [[c:sparks2000]]. Twice-exceptional autistic students thrive with strength- and interest-based teaching [[c:reis2025]], and their parents describe high school as a time when intellectual strengths and social demands diverge sharply [[c:madaus2022]].</p>

<h2><span class="sn">9</span>Intervention</h2>
<p>[[tabref:interv]] summarises the intervention evidence. The oldest demonstration remains one of the most useful: written prompts rapidly increased a hyperlexic child's appropriate spoken responses in natural settings, with maintenance and generalisation [[c:kistner1988]]. The Scaffolding Interrogative Method guides children through structured questions; comprehension rose in each intervention phase and comprehension age increased while reading age did not, closing the hyperlexic gap (secondary summaries report gains of 19.4–36.3% in three months) [[c:ng2014]]. The McGill tablet program trained comprehension at word, phrase and sentence level through word–picture matching with parent support; after a six-week baseline and six weeks of intervention, children with autism and hyperlexia gained significantly more in reading comprehension than typical peers (p = .023), and all groups gained in receptive language ([[figref:mcgill]]) [[c:macdonald2022,mcgillnews]].</p>
[[fig:mcgill]]
[[tab:interv]]
<p>For school-age autistic readers, effective components include question generation, graphic organisers, prediction, anaphoric cueing, explicit instruction and grouping [[c:elzein2014]], and pictorial or graphic representations yield moderate-to-strong effects (Tau-U = 0.85) [[c:lee2025]]. A gifted hyperlexic boy improved markedly with Floortime plus social/pragmatic group speech therapy [[c:stein2015]].</p>
<p>Clinical consensus recommends speech-language therapy, occupational therapy, play-based behavioural approaches and psychological support as needed, together with thoughtful school placement by type [[c:treffertcenter,cleveland]]. Practitioners converge on print-first practice: model language in writing; keep letters and keyboards available (including keyboard-based AAC); turn on subtitles [[c:meaningfulspeech]]; use visual supports for schoolwork, comprehension, communication, self-regulation, executive function, social skills and self-advocacy — "include the written word as much as possible" [[c:nextcomesl]]; exploit rote learning and special interests; break tasks down; and "when in doubt, write it out" [[c:twinkl]]. For <i>wh</i>-questions, present question and answer together, have the child read both, then fade the answer.</p>

<h2><span class="sn">10</span>Allied strengths: numbers, music and languages</h2>
<h3>10.1 Hypernumeracy</h3>
<p>Numbers travel with letters. Autistic children had 3.49 times the odds of a stronger interest in numbers [[c:ostrolenk2024]]; a hypercalculia achievement profile characterised 20% of a national autistic sample [[c:wei2015]]; and case reports pair hyperlexia with hypercalculia and hypermnesia [[c:pacheva2014,etchepareborda2007]]. Reading of number words and Arabic numerals can even dissociate from reading of other words [[c:temple2006]]. Large-number naming offers a bilingual twist ([[tabref:scale]]): English uses the <i>short scale</i> (a new name every 10<sup>3</sup>), while French — including Québec usage — uses the <i>long scale</i> (a new name every 10<sup>6</sup>, with <i>-iard</i> names between). An English nonillion is 10<sup>30</sup>; a French <i>nonillion</i> is 10<sup>54</sup>.</p>
[[tab:scale]]
<h3>10.2 Music</h3>
<p>Music is a relative strength in autism: pitch perception, musical memory and identification of music-evoked emotion [[c:quintin2019]]. Absolute pitch occurs in an estimated 5–11% of autistic people [[c:romani2021]], has been documented in a 4-year-old [[c:brenton2008]], and in one autistic adult extended to naming the pitch of spoken words far better than controls who also had absolute pitch [[c:heaton2008]]. Autistic children recognised basic emotions in music with a relative advantage, while matching peers on faces and voices [[c:sivathasan2023]] — making music a bridge to emotional vocabulary. Physiological responses to music-evoked emotion are reduced in some autistic youth, with age-related differences between 8–11 and 16–18 years [[c:stephenson2016]]. The 2022 Cochrane review (26 studies, 1165 participants) found moderate-certainty benefits of music therapy for global improvement, quality of life and symptom severity, and no clear immediate effect on social interaction or communication ([[figref:cochrane]]) [[c:geretsegger2022]]. Veridical mapping predicts that staff notation — a second orthography mapping symbols to pitches — should be learned with the same ease as print [[c:mottron2013,bouvet2014]].</p>
[[fig:cochrane]]
<h3>10.3 Bilingualism and multilingual hyperlexia</h3>
<p>Hyperlexia crosses scripts: it has been reported in Chinese, Japanese, Kannada, Italian, Spanish, Catalan, Portuguese and English [[c:luo2023,ichiba1990,joshi2010,cossu1986,talero2006,rossello2025,lamonica2013]]. In a Kannada–English bilingual the decoding–comprehension gap appeared in <i>both</i> languages [[c:joshi2010]]. For autistic children, bilingual exposure is not detrimental: in a Montréal study the current amount of exposure to a language explained 62% of variance in vocabulary and 49% in morphology in autistic and typical children alike ([[figref:bilingual]]) [[c:gonzalez2018]], and bilingual autistic children scored in the average monolingual range for receptive vocabulary [[c:gonzalez2019]]. Morphology, including shared Latin and Greek roots, is worth targeting explicitly, since it was the weakest meta-linguistic skill in a hyperlexic Chinese reader [[c:luo2023]].</p>
[[fig:bilingual]]

<h2><span class="sn">11</span>Outcomes across adolescence and adulthood</h2>
<p>Long-term data are sparse but mostly encouraging. Hyperlexia was one of four variables — with known aetiology, Tourette disorder and age — predicting higher IQ and receptive/expressive language in North Dakota's 59 children with PDD, and was proposed as a marker of improvement [[c:fisher1988,burd1987]]. Developmental outcomes of hyperlexic children in a referred sample were comparable to those of peers [[c:grigorenko2002]]. Type 3 features fade, sometimes dramatically [[c:treffert2011,transmitter]]. Preschool hyperlexic traits predicted better expressive and written communication a year later [[c:solazzo2021]], and hyperlexic twins progressed from letter-and-number-only language to full sentences [[c:ostrolenk2023]]. The caution is comprehension: passage comprehension falls further behind with age unless it is taught [[c:wei2015]]. Special skills can be channelled toward employment [[c:etchepareborda2007]] and, according to Treffert, tend to deepen toward creativity rather than disappear [[c:treffert2014]].</p>

<h2><span class="sn">12</span>Design implications: a bilingual, music-integrated game suite</h2>
<p>The evidence yields nine design principles, each applied throughout the accompanying 25-game suite ([[tabref:games]]):</p>
<ol class="principles">
<li><b>P1 Lead with print.</b> Instructions, feedback and social scripts are written first; written prompts increase functional language [[c:kistner1988,meaningfulspeech,nextcomesl]].</li>
<li><b>P2 Bridge code to meaning.</b> Every word found or typed is paired with a definition or picture; semantic knowledge is the largest predictor of comprehension [[c:brown2013,macdonald2022]].</li>
<li><b>P3 Climb the unit ladder.</b> Activities progress from words to sentences to paragraphs, where comprehension breaks down [[c:goldberg1984,snowling1986]].</li>
<li><b>P4 Ask, then prove.</b> Questions require clicking the sentence that proves an answer (question generation, scaffolding) [[c:elzein2014,ng2014]].</li>
<li><b>P5 Make meaning visible.</b> Graphic organisers, timelines, emotion meters and diagrams [[c:lee2025]].</li>
<li><b>P6 Teach the implicit explicitly.</b> Inference, idioms (English and Québécois), tone, sarcasm and perspective [[c:loukusa2018,martelle2022,brown2013]].</li>
<li><b>P7 Harness allied systems.</b> Big numbers, codes and alphabets, staff notation and ear training ride on veridical mapping and music strengths [[c:mottron2013,ostrolenk2024,quintin2019]].</li>
<li><b>P8 Two languages, equal status.</b> Every game runs in English and Québec French; exposure drives vocabulary [[c:gonzalez2018]].</li>
<li><b>P9 Challenge and choice.</b> Difficulty pitched at a strong 17-year-old, free choice among games, optional relaxed (untimed) mode for regulation [[c:reis2025,solis2021,stephenson2016]].</li>
</ol>
[[tab:games]]

<h2><span class="sn">13</span>Limitations</h2>
<p>Most hyperlexia studies are single cases or small groups; definitions and measures vary so much that pooling is inappropriate [[c:zhang2019]]. Adolescent and adult data are scarce. Some older and non-English records could only be summarised from bibliographic data, and a few practice sources are non-peer-reviewed. The SIM percentages come from secondary summaries. This review was compiled by an AI research assistant from publicly indexed abstracts and full texts; it has not been peer-reviewed and is not medical advice — decisions about assessment and therapy belong with qualified clinicians who know the young person.</p>

<h2><span class="sn">14</span>Conclusions</h2>
<p>Sixty years of research converge on a clear picture. Hyperlexia is a powerful, perception-driven print engine that often arrives before speech, frequently travels with numbers and music, and is most common — but not exclusive — in autism. Its limitation is not reading but <i>meaning-making</i>: vocabulary depth, inference, figurative and social language. The best-supported strategy is therefore to write everything out, use print to teach meaning, prove answers from the text, and let adjacent passions — nonillions, ciphers, sonatas, two languages — carry the learner toward the skills that are harder to reach.</p>
'''
